config/routes.rb
Rails.application.routes.draw do
  # ADMIN
  devise_for :admins,
  path: 'admins',
  path_names: {
    sign_in: 'login'
  },
  controllers: {
    sessions: 'admins/sessions',
    registrations: 'admins/registrations'
  }
  authenticate :admin do
    namespace :admins do
      get    '/'                    => 'dashboard#index'
      get    '/settings'            => 'dashboard#settings'
      get    '/api_keys'            => 'dashboard#keys',            as: :api_keys
      post   '/api_key'             => 'dashboard#create_api_key',  as: :api_key
      delete '/api_key/:id'         => 'dashboard#destroy_api_key', as: :destroy_api_key
      get    '/cache'               => 'dashboard#cache_clear',     as: :cache_clear
      get    '/exp_cache'           => 'dashboard#exp_cache_clear', as: :explicit_cache_clear
      get    '/articles'            => 'articles#index'
      get    '/articles/trash'      => 'articles#trash',            as: :articles_trash
      get    '/article/:id'         => 'articles#info',             as: :article_info
      get    '/articles/new'        => 'articles#new',              as: :new_article
      get    '/articles/:id/edit'   => 'articles#edit',             as: :edit_article
      get    '/categories'          => 'categories#index'
      get    '/categories/trash'    => 'categories#trash',          as: :categories_trash
      get    '/category/:id'        => 'categories#info',           as: :category_info
      get    '/categories/new'      => 'categories#new',            as: :new_category
      get    '/categories/:id/edit' => 'categories#edit',           as: :edit_category
      get    '/languages'           => 'languages#index'
      get    '/languages/trash'     => 'languages#trash',           as: :languages_trash
      get    '/language/:id'        => 'languages#info',            as: :language_info
      get    '/languages/new'       => 'languages#new',             as: :new_language
      get    '/languages/:id/edit'  => 'languages#edit',            as: :edit_language
      get    '/tags'                => 'tags#index'
      get    '/tags/trash'          => 'tags#trash',                as: :tags_trash
      get    '/tag/:id'             => 'tags#info',                 as: :tag_info
      get    '/tags/new'            => 'tags#new',                  as: :new_tag
      get    '/tags/:id/edit'       => 'tags#edit',                 as: :edit_tag
      get    '/tools'               => 'tools#index'
      get    '/tools/trash'         => 'tools#trash',               as: :tools_trash
      get    '/tool/:id'            => 'tools#info',                as: :tool_info
      get    '/tools/new'           => 'tools#new',                 as: :new_tool
      get    '/tools/:id/edit'      => 'tools#edit',                as: :edit_tool
    end
  end

  # ARTICLES
  resources :articles, except: %i[index new edit]
  get '/blog' => 'articles#index',          as: :blog
  get '/blog/tag/:id' => 'articles#tagged', as: :blog_tag
  match '/articles/:id/publish' => 'articles#publish', via: %i[put patch], as: :publish_article
  match '/articles/:id/feature' => 'articles#feature', via: %i[put patch], as: :feature_article
  match '/articles/:id/delete'  => 'articles#delete',  via: %i[put patch], as: :delete_article

  # CATEGORIES
  resources :categories, except: %i[index show new edit]
  match '/categories/:id/approve' => 'categories#approve', via: %i[put patch], as: :approve_category
  match '/categories/:id/feature' => 'categories#feature', via: %i[put patch], as: :feature_category
  match '/categories/:id/delete'  => 'categories#delete',  via: %i[put patch], as: :delete_category

  # LANGUAGES
  resources :languages, except: %i[index show new edit]
  match '/languages/:id/approve' => 'languages#approve', via: %i[put patch], as: :approve_language
  match '/languages/:id/feature' => 'languages#feature', via: %i[put patch], as: :feature_language
  match '/languages/:id/delete'  => 'languages#delete',  via: %i[put patch], as: :delete_language

  # TAGS
  resources :tags, except: %i[index show new edit]
  match '/tags/:id/approve' => 'tags#approve', via: %i[put patch], as: :approve_tag
  match '/tags/:id/feature' => 'tags#feature', via: %i[put patch], as: :feature_tag
  match '/tags/:id/delete'  => 'tags#delete',  via: %i[put patch], as: :delete_tag

  # TOOLS
  resources :tools, except: %i[index show new edit]
  get   '/resource/:id'      => 'tools#show',     as: :resource
  match '/tools/:id/publish' => 'tools#publish', via: %i[put patch], as: :publish_tool
  match '/tools/:id/feature' => 'tools#feature', via: %i[put patch], as: :feature_tool
  match '/tools/:id/delete'  => 'tools#delete',  via: %i[put patch], as: :delete_tool

  # STATIC
  get '/directory'            => 'static#directory', as: :directory
  get '/terms-and-conditions' => 'static#terms',     as: :terms
  get '/privacy-policy'       => 'static#policy',    as: :policy

  # ROOT
  root to: 'static#index'
end

app/models/tool.rb
# Tool
# id
# name         :string :uniq
# slug         :string :uniq
# description  :string
# published    :boolean => false
# published_at :datetime => nil
# featured     :boolean => false
# deleted      :boolean => false
# links        :jsonb => { :website, :github }
# style        :jsonb => {}
# languages    :association => ToolLanguages
# categories   :association => ToolCategories
# created_at   :datetime
# updated_at   :datetime

class Tool < ApplicationRecord
  # Modules
  include Publishing
  include Deletions
  include Features
  include Ordering
  include Slugs
  include Timing
  include Validations

  # Functions
  include ToolsHelper

  # Associations
  has_many :tool_languages, dependent: :destroy
  has_many :languages, through: :tool_languages

  has_many :tool_categories, dependent: :destroy
  has_many :categories, through: :tool_categories

  # Attributes => :jsonb
  store_accessor :links, :website, :github
  store_accessor :style

  # Scopes
  scope :include_assoc, -> { includes(:languages, :categories) }
  scope :joins_assoc, -> { joins(:languages, :categories) }
  scope :active_published, -> {
    is_active.is_published.include_assoc
  }
  scope :active_unpublished, -> {
    is_active.is_unpublished.include_assoc
  }
  scope :active_featured, -> {
    is_active.is_published.is_featured.include_assoc
  }

  # Query
  def self.admin_search(term, filter, page)
    if filter
      filter_check(filter)
      .include_assoc
      .where('tools.name ilike ?', "%#{term}%")
      .paginate(page: page, per_page: 25)
    else
      all_active
      .paginate(page: page, per_page: 25)
    end
  end

  # Query -> Published: filter_check(filter)
  def self.filter_check(filter)
    case filter
    when "published"
      active_published
    when "unpublished"
      active_unpublished
    when "featured"
      active_featured
    else
      is_active
    end
  end

  # Tool.directory_search(Boolean, String, @relation, @relation, Integer)
  def self.directory_search(query, term, languages, categories, page)
    if query
      active_published
      .joins_assoc
      .where('tools.name ilike ?', "%#{term}%")
      .where(tool_languages: { language: languages },
             tool_categories: { category: categories })
      .name_asc
      .paginate(per_page: 15, page: page)
    else
      all_published
      .paginate(per_page: 15, page: page)
    end
  end

  # Cache
  after_commit :tool_cache_clear
  after_destroy :tool_cache_clear

  # Tool.all_active
  def self.all_active
    Rails.cache.fetch('Tool.active') { is_active.created_desc.to_a }
  end
  # Tool.all_inactive - Non-Cache
  def self.all_inactive
    is_inactive.created_desc
  end
  # Tool.all_published
  def self.all_published
    Rails.cache.fetch('Tool.published') { active_published.name_asc.to_a }
  end
  # Tool.all_drafts
  def self.all_drafts
    Rails.cache.fetch('Tool.draft') { active_unpublished.name_asc.to_a }
  end
  # Tool.all_featured
  def self.all_featured
    Rails.cache.fetch('Tool.featured') { active_featured.name_asc.to_a }
  end
  # Tool.slugged(params[:id])
  def self.slugged(id)
    Rails.cache.fetch("Tool.#{id}") { include_assoc.friendly.find(id) }
  end
  # Tool.all_recent
  def self.all_recent
    Rails.cache.fetch('Tool.recent') do
      active_published.published_desc.limit(10).to_a
    end
  end
end

app/controllers/admins/tools_controller.rb
class Admins::ToolsController < Admins::AdminAppController
  before_action :set_tool,       only: %i[info edit]
  before_action :set_languages,  only: %i[new edit]
  before_action :set_categories, only: %i[new edit]

  # GET /admins/tools
  def index
    private_seo('Tools')
    @all = Tool.all_active.count
    @published = Tool.all_published.count
    @drafts = Tool.all_drafts.count
    @featured = Tool.all_featured.count
    @tools = Tool.admin_search(params[:term], params[:filter], params[:page])
  end

  # GET /admins/tools/trash
  def trash
    private_seo('Tools Trash')
    @tools = Tool.all_inactive.paginate(per_page: 25, page: params[:page])
    render template: 'admins/tools/index'
  end

  # GET /admins/tool/:id
  def info
    private_seo('Tool')
  end

  # GET /admins/tools/new
  def new
    private_seo('New Tool')
    @tool = Tool.new
  end

  # GET /admins/tools/:id/edit
  def edit
    private_seo('Edit Tool')
  end

  private

  def set_tool
    @tool = Tool.friendly.include_assoc.find(params[:id])
  end

  def set_languages
    @languages = Language.all_approved
  end

  def set_categories
    @categories = Category.all_approved
  end

  def admin_tools_responder(notice)
    respond_to do |format|
      format.html { redirect_to admins_tools_path }
      format.js
    end
  end

end

app/controllers/tools_controller.rb
class ToolsController < ApplicationController
  before_action :authenticate_admin!, except: %i[show]
  before_action :set_tool,            except: %i[create show]
  before_action :set_languages,       only: %i[create update destroy]
  before_action :set_categories,      only: %i[create update destroy]

  # GET /tools/:id
  def show
    @tool = Tool.slugged(params[:id])
    info_seo(@tool.name, tool_url(@tool), @tool.description)
  end

  # POST /tools
  def create
    @tool = Tool.new(tool_params)

    if @tool.save
      admins_tools_responder('created')
    else
      render template: 'admins/tools/new', layout: 'admin'
    end
  end

  # PATCH/PUT /tools/:id
  def update
    if @tool.update(tool_params)
      admins_tools_responder('updated')
    else
      render template: 'admins/tools/edit', layout: 'admin'
    end
  end

  # PATCH/PUT /tools/:id/publish
  def publish
    @tool.publish_toggle
    admins_tools_responder(@tool.published_check.capitalize)
  end

  # PATCH/PUT /tools/:id/feature
  def feature
    @tool.feature_toggle
    admins_tools_responder(@tool.featured_check.capitalize)
  end

  # PATCH/PUT /tools/:id/delete
  def delete
    @tool.delete_toggle
    admins_tools_responder(@tool.deletion_check.capitalize)
  end

  # DESTROY /tools/:id
  def destroy
    @tool.destroy
    redirect_to admins_tools_trash_path, notice: "Tool destroyed."
  end

  private

  def set_tool
    @tool = Tool.friendly.include_assoc.find(params[:id])
  end

  def set_languages
    @languages = Language.all_approved
  end

  def set_categories
    @categories = Category.all_approved
  end

  def tool_params
    params.require(:tool).permit(:name, :slug, :description,
                                 :published, :published_at, :featured, :deleted,
                                 :links, :website, :github,
                                 :style,
                                 :language_ids => [],
                                 :category_ids => [])
  end

  def admins_tools_responder(notice)
    respond_to do |format|
      format.html do
        redirect_to admins_tools_path,
        notice: "Tool #{notice}."
      end
      format.js
    end
  end

end

app/helpers/tools_helper.rb
module ToolsHelper

  # Tool Cache Clear
  def tool_cache_clear
    Rails.cache.delete('Tool.active')
    Rails.cache.delete('Tool.published')
    Rails.cache.delete('Tool.draft')
    Rails.cache.delete('Tool.featured')
    Rails.cache.delete('Tool.recent')
    Rails.cache.delete("Tool.#{slug}")
  end
  
end

app/views/admins/tools/_category.erb
<div class="admin-info-item-association">
  <span><b>ID</b>: <%= category.id %></span>
  <span><b>Name</b>: <%= link_to category.name, admins_category_info_path(category) %></span>
</div>

app/views/admins/tools/_language.erb
<div class="admin-info-item-association">
  <span><b>ID</b>: <%= language.id %></span>
  <span><b>Name</b>: <%= link_to language.name, admins_language_info_path(language) %></span>
</div>

app/views/admins/tools/_search.html.erb
<%= form_tag(admins_tools_path, method: :get, class: 'admin-search') do %>
  <div class="admin-search-input">
    <%= text_field_tag :term, params[:term], placeholder: 'Search Tools...' %>
    <div class="admin-filter-options">
      <%= radio_button_tag :filter, 'all', filter_check('all', params[:filter]) %>
      <span class="all">All (<%= @all %>)</span>
      <%= radio_button_tag :filter, 'published', filter_check('published', params[:filter]) %>
      <span class="published">Published (<%= @published %>)</span>
      <%= radio_button_tag :filter, 'unpublished', filter_check('unpublished', params[:filter]) %>
      <span>Drafts  (<%= @drafts %>)</span>
      <%= radio_button_tag :filter, 'featured', filter_check('featured', params[:filter]) %>
      <span class="featured">Featured  (<%= @featured %>)</span>
    </div>
    <%= submit_tag 'Search' %>
  </div>
<% end %>

app/views/admins/tools/_tool.erb
<div id="tool-<%= tool.id %>" class="admin-item">
  <div class="admin-item-info xl-col-3-4 lg-col-3-4 md-col-2-3 sm-col-1-2 xs-col-1-1">
    <%= link_to tool.name.truncate(25), resource_path(tool) %>
  </div>

  <div class="admin-item-links xl-col-1-4 lg-col-1-4 md-col-1-3 sm-col-1-2 xs-col-1-1">
    <% unless tool.deleted %>
      <%= link_to admins_edit_tool_path(tool), class: 'edit' do %>
        <%= fa_icon "pencil" %>
      <% end %>
      <%= link_to admins_tool_info_path(tool), class: 'info' do %>
        <%= fa_icon "info" %>
      <% end %>
      <%= link_to publish_tool_path(tool), class: "#{tool.published_check}", method: :put do %>
        <%= fa_icon "check" %>
      <% end %>
      <%= link_to feature_tool_path(tool), class: "#{tool.featured_check}", method: :put do %>
        <%= fa_icon "star" %>
      <% end %>
      <%= link_to delete_tool_path(tool), class: "#{tool.deletion_link}", method: :put do %>
        <%= fa_icon "times" %>
      <% end %>
    <% else %>
      <%= link_to delete_tool_path(tool), class: "#{tool.deletion_link}", method: :put do %>
        <%= fa_icon "heart" %>
      <% end %>
      <%= link_to tool, class: 'delete', method: :delete, data: { confirm: "Are you sure?" } do %>
        <%= fa_icon "trash" %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/admins/tools/edit.html.erb
<div id="admin-<%= controller_name %>-<%= action_name %>" class="admin-page">

  <div class="admin-head">
    <h1>EDIT TOOL</h1>
    <div class="admin-head-options">
      <%= link_to 'BACK', admins_tools_path %>
    </div>
  </div>

  <%= render 'tools/form', tool: @tool %>

</div>

app/views/admins/tools/index.html.erb
<div id="admin-<%= controller_name %>-<%= action_name %>" class="admin-page">
  <div class="admin-head">
    <h1><%= controller_name.upcase %></h1>
    <div class="admin-head-options">
      <% if action_name == 'index' %>
        <%= link_to 'TRASH', admins_tools_trash_path %>
      <% else %>
        <%= link_to 'TOOLS', admins_tools_path %>
      <% end %>
      <%= link_to 'NEW', admins_new_tool_path %>
    </div>
  </div>

  <%= render partial: 'admins/tools/search' if action_name == 'index' %>

  <div class="admin-items">
    <%= will_paginate @tools %>
    <%= render @tools %>
    <%= will_paginate @tools %>
  </div>
</div>

app/views/admins/tools/info.html.erb
<div id="admin-<%= controller_name %>-<%= action_name %>" class="admin-page">

  <div class="admin-head">
    <h1><%= controller_name.upcase %></h1>
    <div class="admin-head-options">
      <%= link_to 'EDIT', admins_edit_tool_path(@tool) %>
      <%= link_to 'BACK', admins_tools_path %>
    </div>
  </div>

  <div class="admin-info-item">
    <div class="container">
      <h2 class="head">Information</h2>
      <p><b>ID:</b> <%= @tool.id %></p>
      <p><b>Name:</b> <%= @tool.name %></p>
      <p><b>Slug:</b> <%= @tool.slug %></p>
      <p><b>Description:</b> <%= @tool.description %></p>
      <p><b>Website:</b> <%= link_to "#{@tool.website}", @tool.website %></p>
      <p><b>Github:</b> <%= link_to "#{@tool.github}", @tool.github %></p>
      <p><b>Published:</b> <%= @tool.published %></p>
      <p><b>Published at:</b> <%= @tool.published_time %> | <%= @tool.published_date %></p>
      <p><b>Featured:</b> <%= @tool.featured %></p>
      <p><b>Deleted:</b> <%= @tool.deleted %></p>
      <p><b>Created at:</b> <%= @tool.created_time %> | <%= @tool.created_date %></p>
      <p><b>Updated at:</b> <%= @tool.updated_time %> | <%= @tool.updated_date %></p>
    </div>
  </div>

  <% if @tool.languages.any? %>
    <div class="admin-info-item">
      <div class="container">
        <h2 class="head">Languages</h2>
        <%= render partial: 'admins/tools/language', collection: @tool.languages, as: :language %>
      </div>
    </div>
  <% end %>

  <% if @tool.categories.any? %>
    <div class="admin-info-item">
      <div class="container">
        <h2 class="head">Categories</h2>
        <%= render partial: 'admins/tools/category', collection: @tool.categories, as: :category %>
      </div>
    </div>
  <% end %>

</div>

app/views/admins/tools/new.html.erb
<div id="admin-<%= controller_name %>-<%= action_name %>" class="admin-page">

  <div class="admin-head">
    <h1>NEW TOOL</h1>
    <div class="admin-head-options">
      <%= link_to 'BACK', admins_tools_path %>
    </div>
  </div>

  <%= render 'tools/form', tool: @tool %>

</div>