config/routes.rb
Rails.application.routes.draw do
  # ADMIN
  devise_for :admins,
  path: 'admins',
  path_names: {
    sign_in: 'login'
  },
  controllers: {
    sessions: 'admins/sessions',
    registrations: 'admins/registrations'
  }
  authenticate :admin do
    namespace :admins do
      get    '/'                    => 'dashboard#index'
      get    '/settings'            => 'dashboard#settings'
      get    '/api_keys'            => 'dashboard#keys',            as: :api_keys
      post   '/api_key'             => 'dashboard#create_api_key',  as: :api_key
      delete '/api_key/:id'         => 'dashboard#destroy_api_key', as: :destroy_api_key
      get    '/cache'               => 'dashboard#cache_clear',     as: :cache_clear
      get    '/exp_cache'           => 'dashboard#exp_cache_clear', as: :explicit_cache_clear
      get    '/articles'            => 'articles#index'
      get    '/articles/trash'      => 'articles#trash',            as: :articles_trash
      get    '/article/:id'         => 'articles#info',             as: :article_info
      get    '/articles/new'        => 'articles#new',              as: :new_article
      get    '/articles/:id/edit'   => 'articles#edit',             as: :edit_article
      get    '/categories'          => 'categories#index'
      get    '/categories/trash'    => 'categories#trash',          as: :categories_trash
      get    '/category/:id'        => 'categories#info',           as: :category_info
      get    '/categories/new'      => 'categories#new',            as: :new_category
      get    '/categories/:id/edit' => 'categories#edit',           as: :edit_category
      get    '/languages'           => 'languages#index'
      get    '/languages/trash'     => 'languages#trash',           as: :languages_trash
      get    '/language/:id'        => 'languages#info',            as: :language_info
      get    '/languages/new'       => 'languages#new',             as: :new_language
      get    '/languages/:id/edit'  => 'languages#edit',            as: :edit_language
      get    '/tags'                => 'tags#index'
      get    '/tags/trash'          => 'tags#trash',                as: :tags_trash
      get    '/tag/:id'             => 'tags#info',                 as: :tag_info
      get    '/tags/new'            => 'tags#new',                  as: :new_tag
      get    '/tags/:id/edit'       => 'tags#edit',                 as: :edit_tag
      get    '/tools'               => 'tools#index'
      get    '/tools/trash'         => 'tools#trash',               as: :tools_trash
      get    '/tool/:id'            => 'tools#info',                as: :tool_info
      get    '/tools/new'           => 'tools#new',                 as: :new_tool
      get    '/tools/:id/edit'      => 'tools#edit',                as: :edit_tool
    end
  end

  # ARTICLES
  resources :articles, except: %i[index new edit]
  get '/blog' => 'articles#index',          as: :blog
  get '/blog/tag/:id' => 'articles#tagged', as: :blog_tag
  match '/articles/:id/publish' => 'articles#publish', via: %i[put patch], as: :publish_article
  match '/articles/:id/feature' => 'articles#feature', via: %i[put patch], as: :feature_article
  match '/articles/:id/delete'  => 'articles#delete',  via: %i[put patch], as: :delete_article

  # CATEGORIES
  resources :categories, except: %i[index show new edit]
  match '/categories/:id/approve' => 'categories#approve', via: %i[put patch], as: :approve_category
  match '/categories/:id/feature' => 'categories#feature', via: %i[put patch], as: :feature_category
  match '/categories/:id/delete'  => 'categories#delete',  via: %i[put patch], as: :delete_category

  # LANGUAGES
  resources :languages, except: %i[index show new edit]
  match '/languages/:id/approve' => 'languages#approve', via: %i[put patch], as: :approve_language
  match '/languages/:id/feature' => 'languages#feature', via: %i[put patch], as: :feature_language
  match '/languages/:id/delete'  => 'languages#delete',  via: %i[put patch], as: :delete_language

  # TAGS
  resources :tags, except: %i[index show new edit]
  match '/tags/:id/approve' => 'tags#approve', via: %i[put patch], as: :approve_tag
  match '/tags/:id/feature' => 'tags#feature', via: %i[put patch], as: :feature_tag
  match '/tags/:id/delete'  => 'tags#delete',  via: %i[put patch], as: :delete_tag

  # TOOLS
  resources :tools, except: %i[index show new edit]
  get   '/resource/:id'      => 'tools#show',     as: :resource
  match '/tools/:id/publish' => 'tools#publish', via: %i[put patch], as: :publish_tool
  match '/tools/:id/feature' => 'tools#feature', via: %i[put patch], as: :feature_tool
  match '/tools/:id/delete'  => 'tools#delete',  via: %i[put patch], as: :delete_tool

  # STATIC
  get '/directory'            => 'static#directory', as: :directory
  get '/terms-and-conditions' => 'static#terms',     as: :terms
  get '/privacy-policy'       => 'static#policy',    as: :policy

  # ROOT
  root to: 'static#index'
end

app/models/language.rb
# Language
# id
# name        :string :uniq
# slug        :string :uniq
# description :string
# approved    :boolean => false
# featured    :boolean => false
# deleted     :boolean => false
# style       :jsonb => {}
# tools       :association => ToolLanguages
# created_at  :datetime
# updated_at  :datetime

class Language < ApplicationRecord
  # Modules
  include Approvals
  include Deletions
  include Features
  include Ordering
  include Slugs
  include Timing
  include Validations

  # Functions
  include LanguagesHelper

  # Associations
  has_many :tool_languages, dependent: :destroy
  has_many :tools, through: :tool_languages

  # Attributes => :jsonb
  store_accessor :style

  # Scopes
  scope :include_assoc,   -> { includes(:tools) }
  scope :active_approved, -> {
    is_active.is_approved.include_assoc
  }
  scope :active_unapproved, -> {
    is_active.is_unapproved.include_assoc
  }
  scope :active_featured, -> {
    is_active.is_approved.is_featured.include_assoc
  }

  # Query
  def self.admin_search(term, filter, page)
    if filter
      filter_check(filter)
      .include_assoc
      .where('languages.name ilike ?', "%#{term}%")
      .paginate(page: page, per_page: 25)
    else
      all_active
      .paginate(page: page, per_page: 25)
    end
  end

  # Query -> filter_check(filter)
  def self.filter_check(filter)
    case filter
    when "approved"
      active_approved
    when "unapproved"
      active_unapproved
    when "featured"
      active_featured
    else
      is_active
    end
  end

  # Directory
  def self.directory_filter(languages)
    if languages
      friendly.find(languages)
    else
      all_approved
    end
  end

  # Cache
  after_commit :language_cache_clear
  after_destroy :language_cache_clear

  # Language.all_active
  def self.all_active
    Rails.cache.fetch('Language.active') { is_active.created_desc.to_a }
  end
  # Language.all_inactive - Non-Cache
  def self.all_inactive
    is_inactive.created_desc
  end
  # Language.all_approved
  def self.all_approved
    Rails.cache.fetch('Language.approved') { active_approved.name_asc.to_a }
  end
  # Language.all_drafts
  def self.all_drafts
    Rails.cache.fetch('Language.draft') { active_unapproved.name_asc.to_a }
  end
  # Language.all_featured
  def self.all_featured
    Rails.cache.fetch('Language.featured') { active_featured.name_asc.to_a }
  end
  # Language.slugged(params[:id])
  def self.slugged(id)
    Rails.cache.fetch("Language.#{id}") { include_assoc.friendly.find(id) }
  end
end

app/controllers/admins/languages_controller.rb
class Admins::LanguagesController < Admins::AdminAppController
  before_action :set_language, only: %i[info edit]

  # GET /admins/langauges
  def index
    private_seo('Languages')
    @all = Language.all_active.count
    @approved = Language.all_approved.count
    @drafts = Language.all_drafts.count
    @featured = Language.all_featured.count
    @languages = Language.admin_search(params[:term], params[:filter], params[:page])
  end

  # GET /admins/languages/trash
  def trash
    private_seo('Languages Trash')
    @languages = Language.all_inactive.paginate(per_page: 25, page: params[:page])
    render template: 'admins/languages/index'
  end

  # GET /admins/language/:id
  def info
    private_seo('Language')
  end

  # GET /admins/languages/new
  def new
    private_seo('New Language')
    @language = Language.new
  end

  # GET /admins/languages/:id/edit
  def edit
    private_seo('Edit Language')
  end

  private

  def set_language
    @language = Language.friendly.include_assoc.find(params[:id])
  end

  def admin_languages_responder(notice)
    respond_to do |format|
      format.html { redirect_to admins_languages_path }
      format.js
    end
  end

end

app/controllers/languages_controller.rb
class LanguagesController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_language, except: %i[create]

  # POST /languages
  def create
    @language = Language.new(language_params)

    if @language.save
      admins_languages_responder('created')
    else
      render template: 'admins/languages/new', layout: 'admin'
    end
  end

  # PATCH/PUT /languages/:id
  def update
    if @language.update(language_params)
      admins_languages_responder('updated')
    else
      render template: 'admins/languages/edit', layout: 'admin'
    end
  end

  # PATCH/PUT /languages/:id/approve
  def approve
    @language.approval_toggle
    admins_languages_responder(@language.approval_check.capitalize)
  end

  # PATCH/PUT /languages/:id/feature
  def feature
    @language.feature_toggle
    admins_languages_responder(@language.featured_check.capitalize)
  end

  # PATCH/PUT /languages/:id/delete
  def delete
    @language.delete_toggle
    admins_languages_responder(@language.deletion_check.capitalize)
  end

  # DESTROY /languages/:id
  def destroy
    @language.destroy
    redirect_to admins_languages_trash_path, notice: "Language destroyed."
  end

  private

  def set_language
    @language = Language.friendly.include_assoc.find(params[:id])
  end

  def language_params
    params.require(:language).permit(:name, :slug, :description,
                                     :approved, :featured, :deleted,
                                     :style)
  end

  def admins_languages_responder(notice)
    respond_to do |format|
      format.html do
        redirect_to admins_languages_path,
        notice: "Language #{notice}."
      end
      format.js
    end
  end

end

app/helpers/languages_helper.rb
module LanguagesHelper

  # Language Cache Clear
  def language_cache_clear
    Rails.cache.delete('Language.active')
    Rails.cache.delete('Language.approved')
    Rails.cache.delete('Language.draft')
    Rails.cache.delete('Language.featured')
    Rails.cache.delete("Language.#{slug}")
  end
  
end

app/views/admins/languages/_language.erb
<div id="lang-<%= language.id %>" class="admin-item">
  <div class="admin-item-info xl-col-3-4 lg-col-3-4 md-col-2-3 sm-col-1-2 xs-col-1-1">
    <%= link_to language.name.truncate(25), language_path(language) %>
  </div>

  <div class="admin-item-links xl-col-1-4 lg-col-1-4 md-col-1-3 sm-col-1-2 xs-col-1-1">
    <% unless language.deleted %>
      <%= link_to admins_edit_language_path(language), class: 'edit' do %>
        <%= fa_icon "pencil" %>
      <% end %>
      <%= link_to admins_language_info_path(language), class: 'info' do %>
        <%= fa_icon "info" %>
      <% end %>
      <%= link_to approve_language_path(language), class: "#{language.approval_check}", method: :put do %>
        <%= fa_icon "check" %>
      <% end %>
      <%= link_to feature_language_path(language), class: "#{language.featured_check}", method: :put do %>
        <%= fa_icon "star" %>
      <% end %>
      <%= link_to delete_language_path(language), class: "#{language.deletion_link}", method: :put do %>
        <%= fa_icon "times" %>
      <% end %>
    <% else %>
      <%= link_to delete_language_path(language), class: "#{language.deletion_link}", method: :put do %>
        <%= fa_icon "heart" %>
      <% end %>
      <%= link_to language, class: 'delete', method: :delete, data: { confirm: "Are you sure?" } do %>
        <%= fa_icon "trash" %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/admins/languages/_search.html.erb
<%= form_tag(admins_languages_path, method: :get, class: 'admin-search') do %>
  <div class="admin-search-input">
    <%= text_field_tag :term, params[:term], placeholder: 'Search Languages...' %>
    <div class="admin-filter-options">
      <%= radio_button_tag :filter, 'all', filter_check('all', params[:filter]) %>
      <span class="all">All (<%= @all %>)</span>
      <%= radio_button_tag :filter, 'approved', filter_check('approved', params[:filter]) %>
      <span class="approved">Approved  (<%= @approved %>)</span>
      <%= radio_button_tag :filter, 'unapproved', filter_check('unapproved', params[:filter]) %>
      <span>Drafts  (<%= @drafts %>)</span>
      <%= radio_button_tag :filter, 'featured', filter_check('featured', params[:filter]) %>
      <span class="featured">Featured  (<%= @featured %>)</span>
    </div>
    <%= submit_tag 'Search' %>
  </div>
<% end %>

app/views/admins/languages/_tool.erb
<div class="admin-info-item-association">
  <span><b>ID</b>: <%= tool.id %></span>
  <span><b>Name</b>: <%= link_to tool.name, admins_tool_info_path(tool) %></span>
</div>

app/views/admins/languages/edit.html.erb
<div id="admin-<%= controller_name %>-<%= action_name %>" class="admin-page">

  <div class="admin-head">
    <h1>EDIT LANGUAGE</h1>
    <div class="admin-head-options">
      <%= link_to 'BACK', admins_languages_path %>
    </div>
  </div>

  <%= render 'languages/form', language: @language %>

</div>

app/views/admins/languages/index.html.erb
<div id="admin-<%= controller_name %>-<%= action_name %>" class="admin-page">
  <div class="admin-head">
    <h1><%= controller_name.upcase %></h1>
    <div class="admin-head-options">
      <% if action_name == 'index' %>
        <%= link_to 'TRASH', admins_languages_trash_path %>
      <% else %>
        <%= link_to 'LANGUAGES', admins_languages_path %>
      <% end %>
      <%= link_to 'NEW', admins_new_language_path %>
    </div>
  </div>

  <%= render partial: 'admins/languages/search' if action_name == 'index' %>

  <div class="admin-items">
    <%= will_paginate @languages %>
    <%= render @languages %>
    <%= will_paginate @languages %>
  </div>
</div>

app/views/admins/languages/info.html.erb
<div id="admin-<%= controller_name %>-<%= action_name %>" class="admin-page">

  <div class="admin-head">
    <h1><%= controller_name.upcase %></h1>
    <div class="admin-head-options">
      <%= link_to 'EDIT', admins_edit_language_path(@language) %>
      <%= link_to 'BACK', admins_languages_path %>
    </div>
  </div>

  <div class="admin-info-item">
    <div class="container">
      <h2 class="head">Information</h2>
      <p><b>ID:</b> <%= @language.id %></p>
      <p><b>Name:</b> <%= @language.name %></p>
      <p><b>Slug:</b> <%= @language.slug %></p>
      <p><b>Description:</b> <%= @language.description %></p>
      <p><b>Approved:</b> <%= @language.approved %></p>
      <p><b>Featured:</b> <%= @language.featured %></p>
      <p><b>Deleted:</b> <%= @language.deleted %></p>
      <p><b>Created at:</b> <%= @language.created_time %> | <%= @language.created_date %></p>
      <p><b>Updated at:</b> <%= @language.updated_time %> | <%= @language.updated_date %></p>
    </div>
  </div>

  <% if @language.tools.any? %>
    <div class="admin-info-item">
      <div class="container">
        <h2 class="head">Tools</h2>
        <%= render partial: 'admins/languages/tool', collection: @language.tools, as: :tool %>
      </div>
    </div>
  <% end %>

</div>

app/views/admins/languages/new.html.erb
<div id="admin-<%= controller_name %>-<%= action_name %>" class="admin-page">

  <div class="admin-head">
    <h1>NEW LANGUAGE</h1>
    <div class="admin-head-options">
      <%= link_to 'BACK', admins_languages_path %>
    </div>
  </div>

  <%= render 'languages/form', language: @language %>

</div>