config/routes.rb
Rails.application.routes.draw do
  # ADMIN
  devise_for :admins,
  path: 'admins',
  path_names: {
    sign_in: 'login'
  },
  controllers: {
    sessions: 'admins/sessions',
    registrations: 'admins/registrations'
  }
  authenticate :admin do
    namespace :admins do
      get    '/'                    => 'dashboard#index'
      get    '/settings'            => 'dashboard#settings'
      get    '/api_keys'            => 'dashboard#keys',            as: :api_keys
      post   '/api_key'             => 'dashboard#create_api_key',  as: :api_key
      delete '/api_key/:id'         => 'dashboard#destroy_api_key', as: :destroy_api_key
      get    '/cache'               => 'dashboard#cache_clear',     as: :cache_clear
      get    '/exp_cache'           => 'dashboard#exp_cache_clear', as: :explicit_cache_clear
      get    '/articles'            => 'articles#index'
      get    '/articles/trash'      => 'articles#trash',            as: :articles_trash
      get    '/article/:id'         => 'articles#info',             as: :article_info
      get    '/articles/new'        => 'articles#new',              as: :new_article
      get    '/articles/:id/edit'   => 'articles#edit',             as: :edit_article
      get    '/categories'          => 'categories#index'
      get    '/categories/trash'    => 'categories#trash',          as: :categories_trash
      get    '/category/:id'        => 'categories#info',           as: :category_info
      get    '/categories/new'      => 'categories#new',            as: :new_category
      get    '/categories/:id/edit' => 'categories#edit',           as: :edit_category
      get    '/languages'           => 'languages#index'
      get    '/languages/trash'     => 'languages#trash',           as: :languages_trash
      get    '/language/:id'        => 'languages#info',            as: :language_info
      get    '/languages/new'       => 'languages#new',             as: :new_language
      get    '/languages/:id/edit'  => 'languages#edit',            as: :edit_language
      get    '/tags'                => 'tags#index'
      get    '/tags/trash'          => 'tags#trash',                as: :tags_trash
      get    '/tag/:id'             => 'tags#info',                 as: :tag_info
      get    '/tags/new'            => 'tags#new',                  as: :new_tag
      get    '/tags/:id/edit'       => 'tags#edit',                 as: :edit_tag
      get    '/tools'               => 'tools#index'
      get    '/tools/trash'         => 'tools#trash',               as: :tools_trash
      get    '/tool/:id'            => 'tools#info',                as: :tool_info
      get    '/tools/new'           => 'tools#new',                 as: :new_tool
      get    '/tools/:id/edit'      => 'tools#edit',                as: :edit_tool
    end
  end

  # ARTICLES
  resources :articles, except: %i[index new edit]
  get '/blog' => 'articles#index',          as: :blog
  get '/blog/tag/:id' => 'articles#tagged', as: :blog_tag
  match '/articles/:id/publish' => 'articles#publish', via: %i[put patch], as: :publish_article
  match '/articles/:id/feature' => 'articles#feature', via: %i[put patch], as: :feature_article
  match '/articles/:id/delete'  => 'articles#delete',  via: %i[put patch], as: :delete_article

  # CATEGORIES
  resources :categories, except: %i[index show new edit]
  match '/categories/:id/approve' => 'categories#approve', via: %i[put patch], as: :approve_category
  match '/categories/:id/feature' => 'categories#feature', via: %i[put patch], as: :feature_category
  match '/categories/:id/delete'  => 'categories#delete',  via: %i[put patch], as: :delete_category

  # LANGUAGES
  resources :languages, except: %i[index show new edit]
  match '/languages/:id/approve' => 'languages#approve', via: %i[put patch], as: :approve_language
  match '/languages/:id/feature' => 'languages#feature', via: %i[put patch], as: :feature_language
  match '/languages/:id/delete'  => 'languages#delete',  via: %i[put patch], as: :delete_language

  # TAGS
  resources :tags, except: %i[index show new edit]
  match '/tags/:id/approve' => 'tags#approve', via: %i[put patch], as: :approve_tag
  match '/tags/:id/feature' => 'tags#feature', via: %i[put patch], as: :feature_tag
  match '/tags/:id/delete'  => 'tags#delete',  via: %i[put patch], as: :delete_tag

  # TOOLS
  resources :tools, except: %i[index show new edit]
  get   '/resource/:id'      => 'tools#show',     as: :resource
  match '/tools/:id/publish' => 'tools#publish', via: %i[put patch], as: :publish_tool
  match '/tools/:id/feature' => 'tools#feature', via: %i[put patch], as: :feature_tool
  match '/tools/:id/delete'  => 'tools#delete',  via: %i[put patch], as: :delete_tool

  # STATIC
  get '/directory'            => 'static#directory', as: :directory
  get '/terms-and-conditions' => 'static#terms',     as: :terms
  get '/privacy-policy'       => 'static#policy',    as: :policy

  # ROOT
  root to: 'static#index'
end

app/models/tag.rb
# Tag
# id
# name        :string :uniq
# slug        :string :uniq
# description :string
# approved    :boolean => false
# featured    :boolean => false
# deleted     :boolean => false
# style       :jsonb => {}
# articles    :association => ArticleTags
# created_at  :datetime
# updated_at  :datetime

class Tag < ApplicationRecord
  # Modules
  include Approvals
  include Deletions
  include Features
  include Ordering
  include Slugs
  include Timing
  include Validations

  # Functions
  include TagsHelper

  # Associations
  has_many :article_tags, dependent: :destroy
  has_many :articles, through: :article_tags

  # Attributes => :jsonb
  store_accessor :style

  # Scopes
  scope :include_assoc, -> { includes(:articles) }
  scope :joins_assoc, -> { joins(:articles) }
  scope :active_approved, -> {
    is_active.is_approved.include_assoc
  }
  scope :active_unapproved, -> {
    is_active.is_unapproved.include_assoc
  }
  scope :active_featured, -> {
    is_active.is_approved.is_featured.include_assoc
  }

  # Query
  def self.admin_search(term, filter, page)
    if filter
      filter_check(filter)
      .include_assoc
      .where('tags.name ilike ?', "%#{term}%")
      .paginate(page: page, per_page: 25)
    else
      all_active
      .paginate(page: page, per_page: 25)
    end
  end

  # Query -> filter_check(filter)
  def self.filter_check(filter)
    case filter
    when "approved"
      active_approved
    when "unapproved"
      active_unapproved
    when "featured"
      active_featured
    else
      is_active
    end
  end

  # Cache
  after_commit :tag_cache_clear
  after_destroy :tag_cache_clear

  # Tag.all_active
  def self.all_active
    Rails.cache.fetch('Tag.active') { is_active.created_desc.to_a }
  end
  # Tag.all_inactive - Non-Cache
  def self.all_inactive
    is_inactive.created_desc
  end
  # Tag.all_approved
  def self.all_approved
    Rails.cache.fetch('Tag.approved') { active_approved.name_asc.to_a }
  end
  # Tag.all_drafts
  def self.all_drafts
    Rails.cache.fetch('Tag.draft') { active_unapproved.name_asc.to_a }
  end
  # Tag.all_featured
  def self.all_featured
    Rails.cache.fetch('Tag.featured') { active_featured.name_asc.to_a }
  end
  # Tag.slugged(params[:id])
  def self.slugged(id)
    Rails.cache.fetch("Tag.#{id}") { friendly.find(id) }
  end
  # @tag.articles_published
  def articles_published
    Rails.cache.fetch("Tag.#{id}.articles") do
      articles.active_published.order(published_at: :desc).to_a
    end
  end
end

app/controllers/admins/tags_controller.rb
class Admins::TagsController < Admins::AdminAppController
  before_action :set_tag, only: %i[info edit]

  # GET /admins/tags
  def index
    private_seo('Tags')
    @all = Tag.all_active.count
    @approved = Tag.all_approved.count
    @drafts = Tag.all_drafts.count
    @featured = Tag.all_featured.count
    @tags = Tag.admin_search(params[:term], params[:filter], params[:page])
  end

  # GET /admins/tags/trash
  def trash
    private_seo('Tags Trash')
    @tags = Tag.all_inactive.paginate(per_page: 25, page: params[:page])
    render template: 'admins/tags/index'
  end

  # GET /admins/tag/:id
  def info
    private_seo('Tag')
  end

  # GET /admins/tags/new
  def new
    private_seo('New Tag')
    @tag = Tag.new
  end

  # GET /admins/tags/:id/edit
  def edit
    private_seo('Edit Tag')
  end

  private

  def set_tag
    @tag = Tag.friendly.include_assoc.find(params[:id])
  end

  def admin_tags_responder(notice)
    respond_to do |format|
      format.html { redirect_to admins_tags_path }
      format.js
    end
  end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_tag, except: %i[create]

  # POST /tags
  def create
    @tag = Tag.new(tag_params)

    if @tag.save
      admins_tags_responder('created')
    else
      render template: 'admins/tags/new', layout: 'admin'
    end
  end

  # PATCH/PUT /tags/:id
  def update
    if @tag.update(tag_params)
      admins_tags_responder('updated')
    else
      render template: 'admins/tags/edit', layout: 'admin'
    end
  end

  # PATCH/PUT /tags/:id/approve
  def approve
    @tag.approval_toggle
    admins_tags_responder(@tag.approval_check.capitalize)
  end

  # PATCH/PUT /tags/:id/feature
  def feature
    @tag.feature_toggle
    admins_tags_responder(@tag.featured_check.capitalize)
  end

  # PATCH/PUT /tags/:id/delete
  def delete
    @tag.delete_toggle
    admins_tags_responder(@tag.deletion_check.capitalize)
  end

  # DESTROY /tags/:id
  def destroy
    @tag.destroy
    redirect_to admins_tags_trash_path, notice: "Tag destroyed."
  end

  private

  def set_tag
    @tag = Tag.friendly.include_assoc.find(params[:id])
  end

  def tag_params
    params.require(:tag).permit(:name, :slug, :description,
                                :approved, :featured, :deleted,
                                :style)
  end

  def admins_tags_responder(notice)
    respond_to do |format|
      format.html do
        redirect_to admins_tags_path,
        notice: "Tag #{notice}."
      end
      format.js
    end
  end

end

app/helpers/tags_helper.rb
module TagsHelper

  # Tag Cache Clear
  def tag_cache_clear
    Rails.cache.delete('Tag.active')
    Rails.cache.delete('Tag.approved')
    Rails.cache.delete('Tag.draft')
    Rails.cache.delete('Tag.featured')
    Rails.cache.delete("Tag.#{slug}")
    Rails.cache.delete("Tag.#{id}.articles")
  end
  
end

app/views/admins/tags/_article.erb
<div class="admin-info-item-association">
  <span><b>ID</b>: <%= article.id %></span>
  <span><b>Name</b>: <%= link_to article.name, admins_article_info_path(article) %></span>
</div>

app/views/admins/tags/_search.html.erb
<%= form_tag(admins_tags_path, method: :get, class: 'admin-search') do %>
  <div class="admin-search-input">
    <%= text_field_tag :term, params[:term], placeholder: 'Search Tags...' %>
    <div class="admin-filter-options">
      <%= radio_button_tag :filter, 'all', filter_check('all', params[:filter]) %>
      <span class="all">All (<%= @all %>)</span>
      <%= radio_button_tag :filter, 'approved', filter_check('approved', params[:filter]) %>
      <span class="approved">Approved  (<%= @approved %>)</span>
      <%= radio_button_tag :filter, 'unapproved', filter_check('unapproved', params[:filter]) %>
      <span>Drafts  (<%= @drafts %>)</span>
      <%= radio_button_tag :filter, 'featured', filter_check('featured', params[:filter]) %>
      <span class="featured">Featured  (<%= @featured %>)</span>
    </div>
    <%= submit_tag 'Search' %>
  </div>
<% end %>

app/views/admins/tags/_tag.erb
<div id="tag-<%= tag.id %>" class="admin-item">
  <div class="admin-item-info xl-col-3-4 lg-col-3-4 md-col-2-3 sm-col-1-2 xs-col-1-1">
    <%= link_to tag.name.truncate(25), tag_path(tag) %>
  </div>

  <div class="admin-item-links xl-col-1-4 lg-col-1-4 md-col-1-3 sm-col-1-2 xs-col-1-1">
    <% unless tag.deleted %>
      <%= link_to admins_edit_tag_path(tag), class: 'edit' do %>
        <%= fa_icon "pencil" %>
      <% end %>
      <%= link_to admins_tag_info_path(tag), class: 'info' do %>
        <%= fa_icon "info" %>
      <% end %>
      <%= link_to approve_tag_path(tag), class: "#{tag.approval_check}", method: :put do %>
        <%= fa_icon "check" %>
      <% end %>
      <%= link_to feature_tag_path(tag), class: "#{tag.featured_check}", method: :put do %>
        <%= fa_icon "star" %>
      <% end %>
      <%= link_to delete_tag_path(tag), class: "#{tag.deletion_link}", method: :put do %>
        <%= fa_icon "times" %>
      <% end %>
    <% else %>
      <%= link_to delete_tag_path(tag), class: "#{tag.deletion_link}", method: :put do %>
        <%= fa_icon "heart" %>
      <% end %>
      <%= link_to tag, class: 'delete', method: :delete, data: { confirm: "Are you sure?" } do %>
        <%= fa_icon "trash" %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/admins/tags/edit.html.erb
<div id="admin-<%= controller_name %>-<%= action_name %>" class="admin-page">

  <div class="admin-head">
    <h1>EDIT TAG</h1>
    <div class="admin-head-options">
      <%= link_to 'BACK', admins_tags_path %>
    </div>
  </div>

  <%= render 'tags/form', tag: @tag %>

</div>

app/views/admins/tags/index.html.erb
<div id="admin-<%= controller_name %>-<%= action_name %>" class="admin-page">
  <div class="admin-head">
    <h1><%= controller_name.upcase %></h1>
    <div class="admin-head-options">
      <% if action_name == 'index' %>
        <%= link_to 'TRASH', admins_tags_trash_path %>
      <% else %>
        <%= link_to 'TAGS', admins_tags_path %>
      <% end %>
      <%= link_to 'NEW', admins_new_tag_path %>
    </div>
  </div>

  <%= render partial: 'admins/tags/search' if action_name == 'index' %>

  <div class="admin-items">
    <%= will_paginate @tags %>
    <%= render @tags %>
    <%= will_paginate @tags %>
  </div>
</div>

app/views/admins/tags/info.html.erb
<div id="admin-<%= controller_name %>-<%= action_name %>" class="admin-page">

  <div class="admin-head">
    <h1><%= controller_name.upcase %></h1>
    <div class="admin-head-options">
      <%= link_to 'EDIT', admins_edit_tag_path(@tag) %>
      <%= link_to 'BACK', admins_tags_path %>
    </div>
  </div>

  <div class="admin-info-item">
    <div class="container">
      <h2 class="head">Information</h2>
      <p><b>ID:</b> <%= @tag.id %></p>
      <p><b>Name:</b> <%= @tag.name %></p>
      <p><b>Slug:</b> <%= @tag.slug %></p>
      <p><b>Description:</b> <%= @tag.description %></p>
      <p><b>Approved:</b> <%= @tag.approved %></p>
      <p><b>Featured:</b> <%= @tag.featured %></p>
      <p><b>Deleted:</b> <%= @tag.deleted %></p>
      <p><b>Created at:</b> <%= @tag.created_time %> | <%= @tag.created_date %></p>
      <p><b>Updated at:</b> <%= @tag.updated_time %> | <%= @tag.updated_date %></p>
    </div>
  </div>

  <% if @tag.articles.any? %>
    <div class="admin-info-item">
      <div class="container">
        <h2 class="head">Articles</h2>
        <%= render partial: 'admins/tags/article', collection: @tag.articles, as: :article %>
      </div>
    </div>
  <% end %>

</div>

app/views/admins/tags/new.html.erb
<div id="admin-<%= controller_name %>-<%= action_name %>" class="admin-page">

  <div class="admin-head">
    <h1>NEW TAG</h1>
    <div class="admin-head-options">
      <%= link_to 'BACK', admins_tags_path %>
    </div>
  </div>

  <%= render 'tags/form', tag: @tag %>

</div>